import Head from "next/head";
import { Alert, Box, Stack, Typography } from "@mui/material";
import SearchBox from "@/components/top/searchBox";
import AdList from "@/components/top/adList";
import { useState } from "react";
import { OutlineAd } from "@/types/ads";

const Top = () => {
  const [outlines, setOutlines] = useState<OutlineAd[]>([]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box component="main">
        <Stack spacing={2} sx={{ mt: 2 }}>
          <Typography variant="h4" component="h2">
            ホーム
          </Typography>
          <Alert severity="info">This is an info alert — check it out!</Alert>
          <SearchBox outlines={outlines} setOutlines={setOutlines} />
          <AdList outlines={outlines} setOutlines={setOutlines} />
        </Stack>
      </Box>
    </>
  );
};

export default Top;
